name: allTheBasics
version: '${project.version}'
main: com.sieadev.allthebasics.AllTheBasics
api-version: 1.20
author: sieadev
description: All the basics your minecraft Server needs
permissions:
  atb:
    children:
      gamemode:
        children:
          creative:
            description: use /gm creative
          spectator:
            description: use /gm spectator
          survival:
            description: use /gm survival
          adventure:
            description: use /gm adventure
      fakeop:
        description: use /fakeop
      heal:
        description: use /healPlayer
      feed:
        description: use /feed
      fly:
        description: use /fly
      freeze:
        description: use /freeze
      teleport:
        description: use /tp
      vanish:
        description: use /vanish
      disguise:
        description:  use /disguise

