name: allTheBasics
version: '${project.version}'
main: com.sieadev.allthebasics.AllTheBasics
api-version: 1.20
author: sieadev
description: All the basics your minecraft Server needs
permissions:
  atb:
    children:
      gamemode:
        children:
          creative:
            description: use /gm creative
          spectator:
            description: use /gm spectator
          survival:
            description: use /gm survival
          adventure:
            description: use /gm adventure
      fakeop:
        description: use /fakeop
      heal:
        description: use /healPlayer
      feed:
        description: use /feed
      fly:
        description: use /fly
      freeze:
        description: use /freeze
      teleport:
        description: use /tp
      vanish:
        description: use /vanish
      disguise:
        description:  use /disguise

commands:
  tp:
    permission: administration.tp
    usage: /tp <player>
    description: Teleport to a player
  heal:
    permission: administration.heal
    usage: /heal <player>
    description: heal a player
    alias: h
  feed:
    permission: administration.feed
    usage: /heal <player>
    description: feed a player
    alias: f
  fakeop:
    permission: administration.fakeop
    usage: /fakeop <player>
    description: give a player fake OP

